server:
  port: 8763
  context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://192.168.3.125:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: 18513999760@163.com
    password: Cc123456
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
########################################

msg:
  subject: Good a day !!!
  text:  Today is good a day.